### ISSUE TITLE
Sort out the startup sequence for consoles, notebooks, and queueserver sessions

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#72]
During this import: https://github.com/aps-8id-dys/bluesky/blob/af8ca959eb5032fda622f2be6d1878f70caebeda/scripts/bs_qs_startup.py#L23

there are imports such as `from ..initialize_bs_tools import ...`:
https://github.com/aps-8id-dys/bluesky/blob/af8ca959eb5032fda622f2be6d1878f70caebeda/src/instrument/plans/mesh_plans.py#L12
https://github.com/aps-8id-dys/bluesky/blob/af8ca959eb5032fda622f2be6d1878f70caebeda/src/instrument/plans/acquire_plans.py#L17
https://github.com/aps-8id-dys/bluesky/blob/af8ca959eb5032fda622f2be6d1878f70caebeda/src/instrument/plans/bdp_demo.py#L44-L45

`initialize_bs_tools .py` has code that builds a `RE` with a BestEffortCallback subscription.  This `bec` uses PyQt5.
We need a way for these plans to import the objects they need yet not create objects which we cannot use with the queueserver.

_Originally posted by @prjemian in https://github.com/aps-8id-dys/bluesky/issues/71#issuecomment-2330283676_

**Comment by prjemian** [comment]
Because the queueserver [should](https://github.com/aps-8id-dys/bluesky/issues/71#issuecomment-2330209625) only have one `RE` object defined.

**Comment by prjemian** [comment]
It's very important for the setup to create [singletons](https://www.geeksforgeeks.org/singleton-pattern-in-python-a-complete-guide/) for the `RE`, `cat`, `bec`, and `sd` objects.  These objects are imported by code in `plans` and possibly others.

Also:

- https://python-patterns.guide/gang-of-four/singleton/
- https://stackabuse.com/creating-a-singleton-in-python/

**Comment by prjemian** [comment]
One problem that comes up repeatedly in testing with simplified startup procedures is this exception when running a very simple plan:

```py
[I 2024-09-13 10:18:33,507 bluesky_queueserver.manager.worker] Starting a plan 'sim_count_plan'.
Halting: skipping cleanup and marking exit_status as 'abort'...
ERROR:bluesky:Run aborted
Traceback (most recent call last):
  File "/home/prjemian/.conda/envs/bstest/lib/python3.12/site-packages/bluesky/run_engine.py", line 1507, in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bstest/lib/python3.12/site-packages/bluesky/preprocessors.py", line 408, in subs_wrapper
    return (yield from finalize_wrapper(_inner_plan(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bluesky.utils.PlanHalt
[E 2024-09-13 10:18:33,516 bluesky_queueserver.manager.worker] The plan failed: Plan failed: No module named 'sip'
```

Verified that `sip` is available:

```bash
(bstest) prjemian@arf:~/.../sandbox/sandbox-8id-bluesky$ conda list sip
# packages in environment at /home/prjemian/.conda/envs/bstest:
#
# Name                    Version                   Build  Channel
pyqt5-sip                 12.13.0         py312h5eee18b_0  
sip                       6.7.12          py312h6a678d5_0  
(bstest) prjemian@arf:~/.../sandbox/sandbox-8id-bluesky$ ipython
Python 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from PyQt5 import sip

```

**Comment by prjemian** [comment]
When that problem does not come up, another is very common:

```py
[I 2024-09-13 12:55:30,832 bluesky_queueserver.manager.manager] Starting the plan:
{'name': 'sim_count_plan',
 'args': [],
 'kwargs': {},
 'user': 'GUI Client',
 'user_group': 'primary',
 'meta': {},
 'item_uid': '5caeb11c-4b69-439d-a5c8-684757feae8b'}.
[I 2024-09-13 12:55:30,834 bluesky_queueserver.manager.worker] Starting execution of a plan ...
[I 2024-09-13 12:55:30,835 bluesky_queueserver.manager.worker] Starting a plan 'sim_count_plan'.
Halting: skipping cleanup and marking exit_status as 'abort'...
ERROR:bluesky:Run aborted
Traceback (most recent call last):
  File "/home/prjemian/.conda/envs/bstest/lib/python3.12/site-packages/bluesky/run_engine.py", line 1507, in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prjemian/.conda/envs/bstest/lib/python3.12/site-packages/bluesky/preprocessors.py", line 408, in subs_wrapper
    return (yield from finalize_wrapper(_inner_plan(),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bluesky.utils.PlanHalt
[E 2024-09-13 12:55:30,844 bluesky_queueserver.manager.worker] The plan failed: Plan failed: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
```

**Comment by prjemian** [comment]
This error comes from the matplotlib package.  In the queueserver documentation, there is reference to qt5 in the context of the [*RE Manager Configuration*](https://blueskyproject.io/bluesky-queueserver/manager_config.html#configuration-files).

```yml
worker:
  use_ipython_kernel: true
  ipython_kernel_ip: auto
  ipython_matplotlib: qt5
```

Tests running `start-re-manager` with this additional YAML configuration configuration show the error goes away with this particular section defined:

```yml
worker:
  use_ipython_kernel: false
  # ipython_kernel_ip: auto
  # ipython_matplotlib: qt5
```

This variation is also successful:

```yml


worker:
  use_ipython_kernel: true
  # ipython_kernel_ip: auto
  ipython_matplotlib: qt5
```

**Comment by prjemian** [comment]
By the way, the plans in use here for testing:

```py
"""For development only."""

__all__ = """
    sim_print_plan
    sim_count_plan
    sim_rel_scan_plan
""".split()

import logging

from bluesky import plan_stubs as bps
from bluesky import plans as bp
from ophyd.sim import motor
from ophyd.sim import noisy_det

logger = logging.getLogger(__name__)
logger.info(__file__)

DEFAULT_MD = {"title": "test run with simulator(s)"}


def sim_count_plan(num: int = 1, imax: float = 10_000, md: dict = DEFAULT_MD):
    logger.info("(%s) %s()", __name__, "sim_count_plan")
    yield from bps.mv(noisy_det.Imax, imax)
    yield from bp.count([noisy_det], num=num, md=md)


def sim_print_plan():
    logger.info("(%s) %s()", __name__, "sim_print_plan")
    yield from bps.null()
    print(f"({__name__}) This is a test.")
    print(f"({__name__})  {motor.position=}  {noisy_det.read()=}.")


def sim_rel_scan_plan(
    span: float = 5,
    num: int = 11,
    imax: float = 10_000,
    md: dict = DEFAULT_MD,
):
    logger.info("(%s) %s()", __name__, "sim_rel_scan_plan")
    yield from bps.mv(noisy_det.Imax, imax)
    yield from bp.rel_scan([noisy_det], motor, -span / 2, span / 2, num=num, md=md)
```

**Comment by prjemian** [comment]
Given the complexity that we see in configuring and starting the queueserver host process (`start-re-manager`), a YAML configuration file might provide the flexibility we want.

Here's my current version in a test sandbox.  (Note the use of relative rather than absolute paths.  This is one of the existing items marked TODO.)

```yml
# Bluesky-Queueserver start-re-manager configuration
# use: 
#   queue-monitor &
#   start-re-manager --config=./qs/config.yml
#
# https://blueskyproject.io/bluesky-queueserver/manager_config.html

network:
  redis_addr: localhost:6379
  redis_name_prefix: qs_default
  zmq_control_addr: tcp://*:60615
  zmq_info_addr: tcp://*:60625
  zmq_publish_console: true

operation:
  # choices: SILENT QUIET NORMAL VERBOSE
  console_logging_level: NORMAL

  # emergency_lock_key: custom_lock_key
  print_console_output: true

  # choices: NEVER ENVIRONMENT_OPEN ALWAYS
  update_existing_plans_and_devices: ENVIRONMENT_OPEN
  
  # choices: NEVER ON_REQUEST ON_STARTUP
  user_group_permissions_reload: ON_STARTUP

run_engine:
  # databroker_config: name_of_databroker_config_file
  use_persistent_metadata: true
  # kafka_server: 127.0.0.1:9092
  # kafka_topic: custom_topic_name
  zmq_data_proxy_addr: localhost:5567

startup:
  keep_re: true
  # startup_module: package.collect  # TODO:  from qs/startup.py
  startup_script: ./qs/startup.py
  existing_plans_and_devices_path: ./qs/
  user_group_permissions_path: ./qs/

worker:
  use_ipython_kernel: true
  # ipython_kernel_ip: auto
  ipython_matplotlib: qt5
```
