### ISSUE TITLE
add flag3ad & flag4ad

### ISSUE THREAD

**Issue by prjemian** [aps-8id-dys/bluesky#79]
Add these two cameras, during our Friday meeting time

**Comment by prjemian** [comment]
iconfig details:

```yaml
  FLAG3:
    # IOC host: s8idioc04:/net/s8iddserv/xorApps/epics/synApps_6_3/ioc/8idSpinnaker/iocBoot/ioc8idSpinnaker/softioc/8idSpinnaker.pl status
    # Same filesystem
    # Spinnaker
    IOC_FILES_ROOT: *BLUESKY_DATA_ROOT
    NAME: flag3ad
    PV_PREFIX: "8idaSoft:flag3:"
  FLAG4:
    # IOC host: s8idnx01:/net/s8iddserv/xorApps/epics/synApps_6_3/ioc/8idAlviumG1/iocBoot/ioc8idAlviumG1_D1/softioc/8idAlviumG1_D1.pl status
    # Same filesystem
    # Alvium
    IOC_FILES_ROOT: *BLUESKY_DATA_ROOT
    NAME: flag4ad
    PV_PREFIX: "8iddSoft:"  # IOC has no "flag4:" part
```
